version: "3.8"

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: ["--dev", "--bind", "0.0.0.0"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "50000-50100:50000-50100/udp"
    networks:
      - rag-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local

networks:
  rag-network:
    driver: bridge